[package]
name = "scope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# gtk = { version = "0.4.7", package = "gtk4" }
regex = "1"
nalgebra = "0.30.1"
symm = { path = "/home/brent/Projects/symm" }